all: dijkstra dial radixheap 

dijkstra: program.c 
		gcc -o dijkstra programs2.c -I -O2
dial: program.c
		gcc -o dial programs2.c -I -O3
radixheap: program.c
		gcc -o radixheap programs2.c -I -O3
#testing: testing.c
#		gcc -o testing testing.c -I -O2
