all: dijkstra dial radixheap testing

dijkstra: program.c 
		gcc -o dijkstra program.c -I -O2
dial: program.c
		gcc -o dial program.c -I -O2
radixheap: program.c
		gcc -o radixheap program.c -I -O2
testing: testing.c
		gcc -o testing testing.c -I -O2